name: CI — build & deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preflight:
    name: Preflight checks
    runs-on: ubuntu-latest
    outputs:
      has_cf_token: ${{ steps.check.outputs.has_cf_token }}
    steps:
      - name: Check required secrets
        id: check
        run: |
          missing=0
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" ]; then
            echo "FIREBASE_SERVICE_ACCOUNT is not set"
            missing=1
          fi
          # Set output for Cloudflare token existence (empty string when missing)
          if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
            echo "has_cf_token=false" >> $GITHUB_OUTPUT
          else
            echo "has_cf_token=true" >> $GITHUB_OUTPUT
          fi
          if [ "$missing" -eq 1 ]; then
            echo "Required secrets are missing; failing preflight"
            exit 1
          fi

  build-client:
    name: Build client
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Build client
        run: npm run build

  build-functions:
    name: Build functions (optional)
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for functions directory
        id: check_funcs
        run: |
          if [ -d functions ]; then
            echo "has_functions=true" >> $GITHUB_OUTPUT
          else
            echo "has_functions=false" >> $GITHUB_OUTPUT
          fi

      - name: Install and build functions
        if: steps.check_funcs.outputs.has_functions == 'true'
        run: |
          cd functions && npm ci && npm run build || true

  deploy-functions:
    name: Deploy to Firebase Functions (optional)
    runs-on: ubuntu-latest
    needs: [ build-client, build-functions ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install functions dependencies
        run: |
          if [ -d functions ]; then
            cd functions && npm ci
          else
            echo "No functions directory found — skipping functions install"
          fi

      - name: Deploy to Firebase Functions
        run: |
          if [ -d functions ]; then
            firebase deploy --only functions:api --project studio-4344422468-c2966 --force
          else
            echo "No functions directory found — skipping firebase functions deploy"
          fi

  deploy-pages:
    name: Deploy to Cloudflare Pages (optional)
    runs-on: ubuntu-latest
    needs: build-client
    if: needs.preflight.outputs.has_cf_token == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # This action needs CLOUDFLARE_API_TOKEN secret to be set in repo settings
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "ninja-recipes"
          directory: "dist/public"
